import type { AffiliateProgram } from '@/types/quiz'

export const affiliatePrograms: AffiliateProgram[] = [
  {
    id: 'hims',
    name: 'Hims',
    concerns: ['ed', 'hairloss', 'mentalhealth', 'general'],
    genders: ['male'],
    pricePoint: 'mid',
    subscriptionOnly: true,
    offersBundle: true,
    acceptsInsurance: false,
    asyncConsult: true,
    monthlyPrice: 'From $25/month',
    affiliateUrl: '/go/hims',
    keyFeatures: [
      'Discreet packaging and delivery',
      'Licensed US doctors',
      'Hair, ED & mental health bundles',
      'Cancel anytime',
    ],
    reviewUrl: '/ed/reviews/hims',
  },
  {
    id: 'roman',
    name: 'Roman',
    concerns: ['ed', 'hairloss', 'testosterone', 'general'],
    genders: ['male'],
    pricePoint: 'mid',
    subscriptionOnly: false,
    offersBundle: true,
    acceptsInsurance: false,
    asyncConsult: true,
    monthlyPrice: 'From $22/month',
    affiliateUrl: '/go/roman',
    keyFeatures: [
      'No video call required',
      'Same-day treatment plans',
      'Generic ED medications available',
      'Free shipping',
    ],
    reviewUrl: '/ed/reviews/roman',
  },
  {
    id: 'ro',
    name: 'Ro',
    concerns: ['ed', 'weightloss', 'hairloss', 'testosterone', 'general'],
    genders: ['male', 'female'],
    pricePoint: 'mid',
    subscriptionOnly: false,
    offersBundle: true,
    acceptsInsurance: false,
    asyncConsult: true,
    monthlyPrice: 'From $34/month',
    affiliateUrl: '/go/ro',
    keyFeatures: [
      'Comprehensive men\'s & women\'s health',
      'GLP-1 weight loss programs',
      'Body program with coaching',
      'No video visit required',
    ],
    reviewUrl: '/ed/reviews/ro',
  },
  {
    id: 'hers',
    name: 'Hers',
    concerns: ['weightloss', 'mentalhealth', 'birthcontrol', 'menopause', 'uti', 'general'],
    genders: ['female'],
    pricePoint: 'mid',
    subscriptionOnly: true,
    offersBundle: true,
    acceptsInsurance: false,
    asyncConsult: true,
    monthlyPrice: 'From $20/month',
    affiliateUrl: '/go/hers',
    keyFeatures: [
      'Women\'s health specialist',
      'Birth control & hormone therapy',
      'Weight loss & GLP-1 programs',
      'Mental health support',
    ],
    reviewUrl: '/womens/reviews/hers',
  },
  {
    id: 'nurx',
    name: 'Nurx',
    concerns: ['birthcontrol', 'uti', 'menopause', 'mentalhealth', 'general'],
    genders: ['female', 'other'],
    pricePoint: 'budget',
    subscriptionOnly: false,
    offersBundle: false,
    acceptsInsurance: true,
    asyncConsult: true,
    monthlyPrice: 'From $0 with insurance',
    affiliateUrl: '/go/nurx',
    keyFeatures: [
      'Accepts most insurance plans',
      'Birth control delivered to door',
      'STI testing kits',
      'LGBTQ+ friendly care',
    ],
    reviewUrl: '/womens/reviews/nurx',
  },
  {
    id: 'betterhelp',
    name: 'BetterHelp',
    concerns: ['mentalhealth', 'general'],
    genders: ['male', 'female', 'other'],
    pricePoint: 'mid',
    subscriptionOnly: true,
    offersBundle: false,
    acceptsInsurance: false,
    asyncConsult: false,
    monthlyPrice: 'From $60/week',
    affiliateUrl: '/go/betterhelp',
    keyFeatures: [
      'World\'s largest online therapy platform',
      'Match with a therapist in 48 hours',
      'Text, voice, and video sessions',
      'Switch therapists anytime',
    ],
    reviewUrl: '/mental/reviews/betterhelp',
  },
  {
    id: 'rexmd',
    name: 'Rex MD',
    concerns: ['ed'],
    genders: ['male'],
    pricePoint: 'budget',
    subscriptionOnly: false,
    offersBundle: false,
    acceptsInsurance: false,
    asyncConsult: true,
    monthlyPrice: 'From $19/month',
    affiliateUrl: '/go/rexmd',
    keyFeatures: [
      'Lowest price ED medication',
      'No subscription needed',
      'Licensed US doctors',
      'Fast shipping',
    ],
    reviewUrl: '/ed/reviews/rex-md',
  },
  {
    id: 'keeps',
    name: 'Keeps',
    concerns: ['hairloss'],
    genders: ['male'],
    pricePoint: 'budget',
    subscriptionOnly: true,
    offersBundle: false,
    acceptsInsurance: false,
    asyncConsult: false,
    monthlyPrice: 'From $21/month',
    affiliateUrl: '/go/keeps',
    keyFeatures: [
      'Hair loss specialists',
      'Finasteride and minoxidil',
      'Ongoing check-ins',
      'Cancel anytime',
    ],
    reviewUrl: '/hair/reviews/keeps',
  },
]

export function getProgramById(id: string): AffiliateProgram | undefined {
  return affiliatePrograms.find((p) => p.id === id)
}

export function getProgramsByIds(ids: string[]): AffiliateProgram[] {
  return ids.map((id) => affiliatePrograms.find((p) => p.id === id)).filter(Boolean) as AffiliateProgram[]
}
